// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTemperatureChange();
void onHumidityChange();
void onLightChange();
void onFanStatusChange();
void onLightStatusChange();
void onLockStatusChange();
void onPirChange();

float temperature;
int humidity;
int light;
bool fanStatus;
bool lightStatus;
bool lockStatus;
bool pir;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(light, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(fanStatus, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(lightStatus, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(lockStatus, READWRITE, ON_CHANGE);
  ArduinoCloud.addProperty(pir, READWRITE, ON_CHANGE);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
